#!/usr/bin/env bash

# Check is SPARK_HOME defined
if [[ -z "${SPARK_HOME}" ]]; then
  echo "Specify the SPARK_HOME environment variable: path to the Spark installation."
  exit 1
fi

# Run the command
jar=`ls target/scala-*/josimtext-*.jar`
${SPARK_HOME}/bin/spark-submit $jar ${@}
