#!/usr/bin/env bash

if which spark-submit > /dev/null; then
  cmd=spark-submit
else
  cmd=${SPARK_HOME:-/opt/spark-2.2.0-bin-hadoop2.7}/bin/spark-submit

  # Test command exists
  which ${cmd} > /dev/null
  if test $? -ne 0; then
    echo
    echo "Error: '\$SPARK_HOME' must be set to a valid spark installation, " \
         "or 'spark-submit' be on your path."
    exit 1
  fi
fi

master="--master local[*]"
jar="target/scala-2.11/josimtext-assembly-0.4.jar"
args="${@}"

${cmd} \
    $master \
    $jar \
    $args
