#!/usr/bin/env bash


# Check is SPARK_HOME defined
if [[ -z "${SPARK_HOME}" ]]; then
  echo "Specify the SPARK_HOME environment variable: path to the Spark installation."
  exit 1
fi

# to be imported from a config file
queue="default"
master="local[*]"
num_executors=4
spark_gb=8

source conf/env.sh

# Run the command
jar=`ls target/scala-*/josimtext-*.jar`
${SPARK_HOME}/bin/spark-submit \
    --queue=$queue \
    --master=$master \
    --num-executors=$num_executors \
    --driver-memory=${spark_gb}g \
    --executor-memory=${spark_gb}g \
    $jar \
    ${@}
